# Configuration du microservice Tourism-Service
server:
  port: 8082

spring:
  application:
    name: tourism-service

  # Configuration MongoDB Atlas
  data:
    mongodb:
      uri: mongodb+srv://musdbi:MS14261998@cluster0.oe4xo87.mongodb.net/msa_tourism?retryWrites=true&w=majority&appName=Cluster0

# Configuration Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# Configuration de logging
logging:
  level:
    org.springframework.data.mongodb: DEBUG
    service: INFO
    controller: INFO