# Configuration simple du microservice Travel-Service
server:
  port: 8083

spring:
  application:
    name: travel-service

  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
    property-naming-strategy: LOWER_CAMEL_CASE
    time-zone: UTC
    date-format: yyyy-MM-dd

  # Configuration Neo4j AuraDB
  neo4j:
    uri: neo4j+s://cb89e083.databases.neo4j.io
    authentication:
      username: neo4j
      password: E5p_PQy5sfZGEC7FSBbhExB6Tbrax-BAGCCrz8rPYV8

services:
  city-service:
    url: http://localhost:8081
  tourism-service:
    url: http://localhost:8082

# Configuration Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# Configuration de logging simple
logging:
  level:
    org.springframework.data.neo4j: INFO
    controller: INFO
    service: INFO