# Configuration simple du microservice POI-Service
server:
  port: 8082

spring:
  application:
    name: poi-service

  # Configuration MongoDB simple
  data:
    mongodb:
      host: localhost
      port: 27017
      database: msa_poi

# Configuration Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# Configuration de logging simple
logging:
  level:
    fr.dauphine.miageif.msa.poiservice: INFO
    org.springframework.web: INFO