server:
  port: 8081

spring:
  application:
    name: city-service

  # Configuration Supabase PostgreSQL
  datasource:
    url: postgresql://postgres:[MicroServices14261998@]@db.ztcevidlhyajldpvjfod.supabase.co:5432/postgres
    driver-class-name: org.postgresql.Driver

  # Configuration JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: create-drop  # Crée les tables automatiquement
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

# Configuration Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# Configuration de logging
logging:
  level:
    fr.dauphine.miageif.msa.cityservice: INFO
    org.springframework.web: INFO